### ISSUE TITLE
Some doubts about the program

### ISSUE THREAD

**Issue by leonaone** [yulisun/IRG-McS#1]
Hello, thank you very much for sharing the program, it has been very helpful to me. Error reported in the running GC folder for example _graphCutMex: IRG McS main \ IRG McS main \ GC \ GC \ graphCutMex. mexw64 'is invalid and the module cannot be found. In addition, in the Run build_graphCutMex. m program, there is an error in eval (mexMd) at the ninth line. Thank you very much and I hope you can help me successfully run this program.

**Comment by yulisun** [comment]
Hello. The error message "mexw64 'is invalid and the module cannot be found" typically indicates that MATLAB is unable to locate or load the .mexw64 file.  Here are several steps you can take to check  the problem: 1) Verify the File Path; 2) Check the MEX Configuration with “mex -setup”; 3) Check for MATLAB Path Conflicts. You can also access the original code of the “graphCutMex” from Professor Anton Osokin's webpage for assistance: https://github.com/aosokin/graphCutMex_BoykovKolmogorov.
